/* The second round of short questions and orders, about the newer modules: participants, budget, run of show,
   files, contracts, checklists, reminders, the event board and the history. Pure parsing, tested in tests/questions2.test.mjs.
   The screens act on the result (runAction in js/screens/actions.js); nothing here reads the store.
   Hebrew word boundaries: (?=\s|$), never \b. No Arabic letters anywhere. */
import { trim, str } from './core.js';
import { loose, polite } from './travel.js';

/* the event name, after "של / ל / באירוע / for / of / pour / de"; alt = without a Hebrew one-letter prefix (ל/ב) */
const OF = loose(/^(?:של\s+|באירוע\s+של\s+|באירוע\s+|לאירוע\s+של\s+|לאירוע\s+|בתיק\s+של\s+|בתיק\s+|מול\s+|עבור\s+|for the event of\s+|for the event\s+|of the event\s+|for\s+|of\s+|on\s+|in\s+|at\s+|with\s+|pour l['’]événement de\s+|pour l['’]événement\s+|pour\s+|de l['’]|de la\s+|des\s+|du\s+|de\s+|d['’]|dans\s+|chez\s+|avec\s+|sur\s+|à\s+|au\s+|aux\s+)/i);
export function whoOf(rest) {
  let who = trim(str(rest)).replace(/[?!.]+$/, '').replace(OF, '').replace(/^(?:the|le|la|les|l['’])\s*/i, '').trim();
  who = who.replace(loose(/^(?:ה?אירוע|ה?תיק|event|case|dossier|événement|projet|project)\s+(?:של|of|de|du)?\s*/i), '').replace(/[?!.]+$/, '').trim();
  const alt = /^[לב][֐-׿]/.test(who) ? who.slice(1) : who;
  return { who, alt };
}

const Q = '[״"\'׳]?'; // "לו״ז" is written with a gershayim, a quote, or nothing
const LIST = '(?:רשימת\\s+(?:ה)?תיוג|רשימת\\s+(?:ה)?בדיקה|רשימה|צ[\'׳]?ק\\s*ליסט)';
const DOC_HE = '(תפריט|תפריטים|חוזה|הסכם|הצעת\\s+(?:ה)?מחיר|הצעה|הצעות|ביטוח|אישור\\s+(?:ה)?ביטוח|חשבונית|חשבוניות|קבלה|קבלות|תמונות|תמונה|צילומים|תוכנית|תכנית|לו' + Q + 'ז|קובץ|קבצים|מסמך|מסמכים|היתר|רישיון|רשיון)';
const DOC_EN = '(menus?|contracts?|agreements?|quotes?|quotations?|insurance|invoices?|receipts?|photos?|pictures?|plans?|schedule|files?|documents?|permits?|licen[cs]es?)';
const DOC_FR = '(menus?|contrats?|devis|assurance|factures?|reçus?|recus?|photos?|plans?|programme|fichiers?|documents?|permis|autorisations?)';

const R = [
  // participants
  ['partAdd', new RegExp('^(?:הוסיפי|תוסיפי|הוסף|רשמי|תרשמי)\\s+(?:משתתף|משתתפת|משתתפים|משתתפות|אורח|אורחת|אורחים)\\s+(?:ל|ב|לרשימה\\s+של\\s+|לרשימת\\s+)(.+?)\\s*:\\s*([\\s\\S]+)$|^(?:add|register|put|sign up|enter)\\s+(?:a\\s+|the\\s+|these\\s+|new\\s+)?(?:participants?|guests?|attendees?|people|names?)\\s+(?:to|for|on|in)\\s+(?:the\\s+list\\s+of\\s+|the\\s+)?(.+?)\\s*:\\s*([\\s\\S]+)$|^(?:ajoute|inscris|ajouter|inscrire|mets|enregistre)\\s+(?:un|une|des|le|la|les|ces|cette)?\\s*(?:participant(?:e|s|es)?|invité(?:e|s|es)?|personnes?|noms?)\\s+(?:à|a|pour|dans|sur|au|aux)\\s+(?:la\\s+liste\\s+de\\s+|la\\s+liste\\s+d\')?(.+?)\\s*:\\s*([\\s\\S]+)$', 'i')],
  ['rsvpCount', /^כמה\s+(?:כבר\s+)?(?:אישרו(?:\s+הגעה)?|אנשים\s+אישרו(?:\s+הגעה)?|מגיעים|מגיעות|יגיעו|אנשים\s+מגיעים|משתתפים\s+מגיעים|אישורי\s+הגעה\s+יש)\s+(.+)$|^how\s+many\s+(?:people\s+|guests\s+|participants\s+|attendees\s+)?(?:have\s+|are\s+|will\s+|already\s+)?(?:confirmed|coming|come|attending|attend|rsvp'?d|rsvps?|replied\s+yes|said\s+yes)\s+(?:for|to|at)?\s*(.+)$|^combien\s+(?:de\s+)?(?:personnes\s+|gens\s+|participants\s+|invités\s+)?(?:ont\s+|sont\s+|vont\s+|seront\s+)?(?:confirmé|confirment|viennent|venir|présents|présentes|là|inscrits|de\s+confirmations?|de\s+confirmés)\s+(?:pour|à|a|au)?\s*(.+)$/i],
  ['rsvpMissing', /^מי\s+(?:עוד\s+|עדיין\s+)?לא\s+(?:אישר|אישרו|אישרה)(?:\s+הגעה)?\s+(.+)$|^who\s+(?:has\s+not|hasn't|have\s+not|haven't|did\s+not|didn't|still\s+hasn't|still\s+haven't)\s+(?:confirmed|rsvp'?d|replied|answered|responded)(?:\s+yet)?\s+(?:for|to)?\s*(.+)$|^qui\s+n'(?:a|ont)\s+pas\s+(?:encore\s+)?(?:confirmé|répondu)\s+(?:pour|à|a)?\s*(.+)$/i],
  ['hotelList', /^(?:(?:תכיני|הכיני|תני\s+לי|תראי\s+לי|הראי\s+לי)\s+(?:את\s+)?)?(?:ה)?(?:רשימה\s+למלון|רשימת\s+(?:ה)?חדרים|רשימת\s+(?:ה)?לינה|רשימה\s+ללינה)\s+(?:של\s+|ל|ב)?(.+)$|^(?:(?:prepare|make|show\s+me|give\s+me|send\s+me|build)\s+)?(?:the\s+)?(?:rooming\s+list|hotel\s+list|room\s+list|accommodation\s+list|list\s+for\s+the\s+hotel)\s+(?:for|of)\s+(.+)$|^(?:(?:prépare|prepare|montre-moi|donne-moi|fais-moi|fais|envoie-moi)\s+)?(?:la\s+)?(?:rooming\s+list|liste\s+(?:pour\s+)?(?:l'|de\s+l')?hôtel|liste\s+des\s+chambres|liste\s+hôtel|liste\s+hébergement|liste\s+d'hébergement)\s+(?:pour|de|d')\s*(.+)$/i],
  // budget
  ['budgetProfit', /^(?:מה|כמה)\s+(?:ה)?(?:רווח|רווחיות|מרווח|מרג['׳]?ין)\s+(.+)$|^(?:what(?:'s|\s+is)\s+(?:the\s+|our\s+)?(?:margin|profit|profitability|profit\s+margin)|how\s+much\s+(?:do\s+we|will\s+we|are\s+we\s+going\s+to)\s+(?:make|earn)|how\s+much\s+profit(?:\s+is\s+there)?)\s+(?:on|of|for|from|in)?\s*(.+)$|^(?:quelle\s+est\s+(?:la\s+|notre\s+)?(?:marge|rentabilité)|quel\s+est\s+(?:le\s+|notre\s+)?(?:bénéfice|profit|gain)|combien\s+(?:on\s+gagne|gagne-t-on|on\s+se\s+fait|on\s+marge)|ça\s+rapporte\s+combien)\s+(?:sur|de|pour|d'|avec)?\s*(.+)$/i],
  ['budgetCost', /^(?:כמה|מה)\s+(?:עולים|עולה|עולות|עלות|העלות\s+של)\s+(?:לנו\s+|לי\s+)?(?:ה)?(?:ספקים|ספק|ספקי)\s+(.+)$|^(?:how\s+much\s+(?:do|are|will)\s+(?:the\s+)?suppliers\s+cost(?:ing)?(?:\s+us)?|what\s+(?:do|are)\s+(?:the\s+)?suppliers\s+cost(?:ing)?(?:\s+us)?|what(?:'s|\s+is)\s+(?:the\s+)?(?:total\s+)?(?:supplier|suppliers'?|vendor)\s+cost)\s+(?:for|of|on|in)?\s*(.+)$|^(?:combien\s+(?:nous\s+|me\s+)?coûtent\s+les\s+fournisseurs|quel\s+est\s+le\s+coût\s+(?:total\s+)?(?:des\s+)?fournisseurs|ça\s+coûte\s+combien\s+(?:en|les)\s+fournisseurs)\s+(?:pour|de|sur|d'|à)?\s*(.+)$/i],
  ['budgetSchedule', /^(?:מה|תראי\s+לי\s+את|הראי\s+לי\s+את)\s+(?:ה)?לוח\s+(?:ה)?תשלומים\s+(.+)$|^(?:what(?:'s|\s+is)\s+(?:the\s+)?(?:payment\s+schedule|payment\s+plan|payment\s+dates|schedule\s+of\s+payments)|show\s+me\s+(?:the\s+)?(?:payment\s+schedule|payment\s+plan|payment\s+dates)|when\s+are\s+the\s+payments)\s+(?:for|of|on)?\s*(.+)$|^(?:quel\s+est\s+l'échéancier|montre-moi\s+l'échéancier|c'est\s+quoi\s+l'échéancier|quel\s+est\s+le\s+(?:calendrier|plan)\s+des?\s+paiements?|montre-moi\s+le\s+(?:calendrier|plan)\s+des?\s+paiements?|quand\s+sont\s+les\s+paiements)\s+(?:de|pour|d')?\s*(.+)$/i],
  ['budgetOpen', /^(?:כמה|מה)\s+(?:עוד\s+)?(?:פתוח|נשאר)\s+(?:לתשלום|לשלם|לגבות|לקבל|בתשלומים|מול\s+הלקוח)\s+(.+)$|^how\s+much\s+(?:is\s+)?(?:still\s+)?(?:open|outstanding|left\s+to\s+(?:pay|collect|receive)|unpaid|due|owed|remaining|left)\s+(?:for|on|of|in|from)?\s*(.+)$|^what(?:'s|\s+is)\s+(?:still\s+)?(?:open|outstanding|left\s+to\s+(?:pay|collect)|unpaid|due|owed)\s+(?:for|on|of|in|from)\s+(.+)$|^(?:combien\s+(?:reste|reste-t-il|il\s+reste|il\s+me\s+reste|on\s+doit\s+encore|le\s+client\s+doit\s+encore)(?:\s+à\s+(?:payer|encaisser|recevoir))?|qu'est-ce\s+qui\s+reste\s+à\s+(?:payer|encaisser)|qu'est-ce\s+qu'il\s+reste\s+à\s+(?:payer|encaisser))\s+(?:pour|sur|de|d'|à)?\s*(.+)$/i],
  // run of show
  ['rsNow', new RegExp('^(?:מה\\s+(?:קורה\\s+)?עכשיו(?:\\s+(?:ב|לפי\\s+|על\\s+פי\\s+)(?:ה)?לו' + Q + 'ז)?|מה\\s+(?:ה)?(?:שלב|בלוק)\\s+(?:הנוכחי|עכשיו)|איפה\\s+אנחנו\\s+בלו' + Q + 'ז)\\s*$|^(?:what(?:\'s|\\s+is)\\s+(?:on\\s+|happening\\s+|going\\s+on\\s+)?(?:right\\s+)?now(?:\\s+(?:on|in)\\s+the\\s+(?:run\\s*sheet|schedule|run\\s+of\\s+show|programme|program))?|where\\s+are\\s+we\\s+(?:on|in|at)\\s+the\\s+(?:run\\s*sheet|schedule|programme|program)|what(?:\'s|\\s+is)\\s+the\\s+current\\s+(?:block|step|item|slot))\\s*$|^(?:qu\'est-ce\\s+qu\'il\\s+y\\s+a|qu\'est-ce\\s+qui\\s+se\\s+passe|on\\s+en\\s+est\\s+où|où\\s+on\\s+en\\s+est|où\\s+en\\s+est-on|c\'est\\s+quoi)\\s+(?:maintenant|là|en\\s+ce\\s+moment)(?:\\s+(?:au|dans\\s+le|sur\\s+le)\\s+(?:programme|déroulé|planning))?\\s*$|^(?:on\\s+en\\s+est\\s+où|où\\s+on\\s+en\\s+est|où\\s+en\\s+est-on|quel\\s+est\\s+le\\s+bloc\\s+actuel|c\'est\\s+quoi\\s+le\\s+bloc\\s+actuel)(?:\\s+(?:au|dans\\s+le|sur\\s+le)\\s+(?:programme|déroulé|planning))?\\s*$', 'i')],
  ['rsNext', new RegExp('^(?:מה\\s+(?:ה)?(?:הבא|בא)(?:\\s+(?:בתור|אחר\\s+כך))?(?:\\s+ב(?:ה)?לו' + Q + 'ז)?|מה\\s+(?:ה)?(?:שלב|בלוק)\\s+הבא(?:\\s+בלו' + Q + 'ז)?)\\s*$|^(?:(?:and\\s+)?(?:what(?:\'s|\\s+is)\\s+(?:up\\s+)?next|what\\s+next|what\\s+comes\\s+next|what\\s+follows|what(?:\'s|\\s+is)\\s+after(?:\\s+that|\\s+this)?|then\\s+what|what\\s+then|then|next\\s+step|next\\s+block|next)(?:\\s+(?:on|in)\\s+the\\s+(?:run\\s*sheet|schedule|run\\s+of\\s+show|programme|program))?)\\s*$|^(?:(?:et\\s+)?(?:(?:qu\'est-ce\\s+qu\'il\\s+y\\s+a|c\'est\\s+quoi|qu\'est-ce\\s+qui\\s+vient)\\s+)?(?:après|ensuite|la\\s+suite|le\\s+bloc\\s+suivant|l\'étape\\s+suivante|le\\s+prochain\\s+bloc)(?:\\s+(?:au|dans\\s+le|sur\\s+le)\\s+(?:programme|déroulé|planning))?)\\s*$', 'i')],
  ['callSheet', /^(?:(?:תכיני|הכיני|תשלחי|שלחי|תני|תראי\s+לי|prepare|make|send|show\s+me|prépare|prepare|envoie|montre-moi)\s+)?(?:את\s+|the\s+|la\s+|une\s+)?(?:דף\s+(?:ה)?קריאה|call\s*sheet|feuille\s+de\s+route)\s+(?:ל|של\s+|for\s+|of\s+|to\s+|pour\s+|de\s+|d['’]|à\s+)(.+?)(?:\s+(?:ל|לאירוע\s+(?:של\s+)?|באירוע\s+(?:של\s+)?|של\s+|for\s+(?:the\s+event\s+(?:of\s+)?)?|pour\s+(?:l['’]événement\s+(?:de\s+)?)?|de\s+|d['’]|à\s+)(.+))?$/i],
  ['live', /^(?:(?:עברי|תעברי|עבור|לכי|תלכי|תפתחי|פתחי|הפעילי|תפעילי)\s+(?:ל|את\s+)?)?(?:מצב\s+)?יום\s+האירוע(?:\s+(?:של\s+|ל)(.+))?$|^(?:(?:go\s+to|switch\s+to|open|start|turn\s+on|enter)\s+(?:the\s+)?)?(?:day[- ]of(?:\s+mode)?|event\s+day(?:\s+mode)?|live\s+mode|live\s+view|show\s+mode)(?:\s+(?:for|of)\s+(.+))?$|^(?:(?:passe|va|ouvre|lance|mets|mets-toi|bascule)\s+(?:en|au|le|sur\s+le)\s+)?mode\s+(?:jour[- ]j|live|direct|jour\s+de\s+l'événement)(?:\s+(?:pour|de|d')\s*(.+))?$|^(?:jour[- ]j|le\s+jour\s+j)(?:\s+(?:pour|de|d')\s*(.+))?$/i],
  // files
  ['docsMissing', /^(?:מה|אילו|איזה)\s+(?:עוד\s+)?(?:חסר|חסרים)\s+(?:לי\s+)?(?:ב|מ)?(?:ה)?(?:מסמכים|קבצים|ניירת)\s+(.+)$|^(?:מה|אילו|איזה)\s+(?:מסמכים|קבצים)\s+(?:עוד\s+)?חסרים\s+(.+)$|^(?:what|which)\s+(?:documents?|files?|papers?|paperwork)\s+(?:are|is)\s+(?:still\s+)?missing\s+(?:for|in|on|of|from)?\s*(.+)$|^what(?:'s|\s+is)\s+(?:still\s+)?missing\s+(?:in|from)\s+the\s+(?:documents?|files?|papers?|paperwork)\s+(?:of|for)?\s*(.+)$|^(?:quels?\s+(?:documents?|fichiers?|papiers?)\s+(?:manquent?|il\s+manque)|qu'est-ce\s+qui\s+manque\s+dans\s+les\s+(?:documents?|fichiers?|papiers?)|que\s+manque-t-il\s+dans\s+les\s+(?:documents?|fichiers?|papiers?)|il\s+manque\s+quoi\s+(?:comme|dans\s+les)\s+(?:documents?|fichiers?|papiers?)|qu'est-ce\s+qu'il\s+manque\s+(?:comme|dans\s+les)\s+(?:documents?|fichiers?|papiers?))\s+(?:pour|à|de|d'|dans)?\s*(.+)$/i],
  ['fileFind', new RegExp('^(?:איפה|היכן|תמצאי\\s+לי|תמצאי|מצאי)\\s+(?:את\\s+)?(?:ה)?' + DOC_HE + '\\s+(?:של|ל|ב|מ)\\s*(.+)$|^(?:where(?:\'s|\\s+is|\\s+are)|find(?:\\s+me)?|show\\s+me)\\s+(?:the\\s+)?' + DOC_EN + '\\s+(?:of|for|from|in)\\s+(.+)$|^(?:où\\s+(?:est|sont)|trouve(?:-moi)?|montre-moi)\\s+(?:le|la|les|l[\'’])?\\s*' + DOC_FR + '\\s+(?:de|du|pour|d[\'’])\\s*(.+)$', 'i')],
  // contracts
  ['contractMissing', /^(?:מה|איזה|אילו)\s+(?:עוד\s+)?(?:חסר|חסרים)\s+(?:לי\s+)?(?:ל|ב)(?:ה)?(?:חוזה|הסכם)\s+(.+)$|^what(?:'s|\s+is)\s+(?:still\s+)?missing\s+(?:for|in|on|from)\s+the\s+(?:contract|agreement)\s+(?:of|for|with)?\s*(.+)$|^(?:que\s+manque-t-il|qu['’]est-ce\s+qui\s+manque|qu['’]est-ce\s+qu['’]il\s+manque)\s+(?:au|dans\s+le|pour\s+le|sur\s+le)\s+contrat\s+(?:de|pour|avec|d['’])?\s*(.+)$/i],
  ['contractSigned', /^(?:האם\s+)?(?:ה)?(?:חוזה|הסכם)\s+(?:של\s+|עם\s+|ל)(.+?)\s+(?:כבר\s+)?(?:חתום|נחתם)$|^(?:האם\s+)?(.+?)\s+(?:כבר\s+)?(?:חתם|חתמו|חתמה)\s+(?:על\s+)?(?:ה)?(?:חוזה|הסכם)$|^(?:is|has)\s+the\s+(?:contract|agreement)\s+(?:of|for|with)\s+(.+?)\s+(?:been\s+)?signed(?:\s+yet)?$|^(?:did|has)\s+(.+?)\s+sign(?:ed)?\s+the\s+(?:contract|agreement)(?:\s+yet)?$|^(?:est-ce\s+que\s+)?le\s+contrat\s+(?:de|avec|pour|d')\s*(.+?)\s+(?:est(?:-il)?|a\s+été)\s+(?:déjà\s+)?signé$|^(?:est-ce\s+que\s+)?(.+?)\s+a(?:-t-il|-t-elle)?\s+(?:déjà\s+)?signé\s+le\s+contrat$/i],
  // checklists
  ['checklistWeek', new RegExp('^(?:מה\\s+(?:יש\\s+)?(?:לשבוע\\s+הקרוב|השבוע|לשבוע\\s+הזה|בשבוע\\s+הקרוב|לימים\\s+הקרובים|דחוף)|מה\\s+(?:צריך|יש)\\s+לעשות\\s+(?:השבוע|בשבוע\\s+הקרוב))\\s+ב(?:ה)?' + LIST + '\\s+(.+)$|^what(?:\'s|\\s+is)\\s+(?:due|up|on|left|to\\s+do)\\s+(?:this|next|for\\s+the\\s+coming|for\\s+this|in\\s+the\\s+coming)\\s+(?:week|days)\\s+(?:on|in)\\s+the\\s+(?:checklist|check-list|list)\\s+(?:of|for)?\\s*(.+)$|^what(?:\'s|\\s+is)\\s+(?:due|up|on|left)\\s+(?:on|in)\\s+the\\s+(?:checklist|check-list|list)\\s+(?:this|next)\\s+week\\s+(?:of|for)?\\s*(.+)$|^(?:qu\'est-ce\\s+qu\'il\\s+y\\s+a|qu\'y\\s+a-t-il|que\\s+faire|qu\'est-ce\\s+qu\'il\\s+y\\s+a\\s+à\\s+faire|qu\'est-ce\\s+qui\\s+est\\s+prévu)\\s+(?:pour\\s+)?(?:cette\\s+semaine|la\\s+semaine\\s+prochaine|ces\\s+prochains\\s+jours|dans\\s+les\\s+prochains\\s+jours)\\s+(?:sur|dans)\\s+la\\s+(?:check-?list|liste)\\s+(?:de|pour|d\')?\\s*(.+)$', 'i')],
  ['checklistLeft', new RegExp('^(?:מה\\s+(?:עוד\\s+)?(?:נשאר|פתוח|לא\\s+סומן|לא\\s+בוצע)|מה\\s+(?:ה)?מצב)\\s+(?:לי\\s+)?ב(?:ה)?' + LIST + '\\s+(.+)$|^what(?:\'s|\\s+is)\\s+(?:still\\s+)?(?:left|open|remaining|not\\s+done|to\\s+do|unchecked)\\s+(?:on|in)\\s+the\\s+(?:checklist|check-list|list)\\s+(?:of|for)?\\s*(.+)$|^what\\s+remains\\s+(?:on|in)\\s+the\\s+(?:checklist|check-list|list)\\s+(?:of|for)?\\s*(.+)$|^(?:que\\s+reste-t-il|qu\'est-ce\\s+qui\\s+reste|qu\'est-ce\\s+qu\'il\\s+reste|il\\s+reste\\s+quoi|qu\'est-ce\\s+qu\'il\\s+reste\\s+à\\s+faire|qu\'est-ce\\s+qui\\s+n\'est\\s+pas\\s+fait)\\s+(?:sur|dans)\\s+la\\s+(?:check-?list|liste(?:\\s+de\\s+contrôle)?)\\s+(?:de|pour|d\')?\\s*(.+)$', 'i')],
  // reminders
  ['remindersRead', /^(?:סמני|תסמני|סימני)\s+(?:את\s+)?(?:כל\s+)?(?:ה)?(?:תזכורות|התראות)\s+(?:כ)?(?:נקראו|נקרא|טופלו)$|^(?:mark\s+(?:all\s+)?(?:the\s+|my\s+)?(?:reminders|notifications|alerts)\s+(?:as\s+)?(?:read|seen|done)|mark\s+(?:everything|all)\s+(?:as\s+)?read)$|^(?:marque\s+(?:tous\s+|toutes\s+)?(?:les|mes)\s+(?:rappels|notifications|alertes)\s+comme\s+(?:lus?|lues|vus?|vues)|marque\s+tout\s+comme\s+lu|tout\s+est\s+lu)$/i],
  ['urgent', /^(?:מה\s+דחוף(?:\s+(?:עכשיו|היום))?|יש\s+משהו\s+דחוף|מה\s+הדחוף)$|^(?:what(?:'s|\s+is)\s+urgent(?:\s+(?:now|today|right\s+now))?|anything\s+urgent(?:\s+today)?|is\s+there\s+anything\s+urgent|what\s+needs\s+attention(?:\s+now)?)$|^(?:qu'est-ce\s+qui\s+est\s+urgent(?:\s+(?:là|aujourd'hui|maintenant))?|quoi\s+d'urgent|c'est\s+quoi\s+l'urgent|y\s+a-t-il\s+(?:quelque\s+chose\s+d')?urgent|il\s+y\s+a\s+(?:quelque\s+chose\s+d')?urgent|urgences?|les\s+urgences)$/i],
  ['reminders', /^(?:מה\s+(?:ה)?(?:תזכורות|התראות)(?:\s+שלי)?|(?:ה)?(?:תזכורות|התראות)\s+שלי|יש\s+(?:לי\s+)?תזכורות)$|^(?:what\s+are\s+my\s+(?:reminders|notifications|alerts)|my\s+(?:reminders|notifications|alerts)|any\s+(?:reminders|notifications)|show\s+(?:me\s+)?(?:my\s+)?(?:reminders|notifications)|do\s+i\s+have\s+(?:any\s+)?(?:reminders|notifications))$|^(?:quels\s+sont\s+mes\s+(?:rappels|notifications)|mes\s+(?:rappels|notifications|alertes)|qu'est-ce\s+que\s+j'ai\s+comme\s+(?:rappels|notifications)|il\s+y\s+a\s+des\s+(?:rappels|notifications)|montre(?:-moi)?\s+mes\s+(?:rappels|notifications)|j'ai\s+des\s+rappels)$/i],
  // event board
  ['caseMove', /^(?:העבירי|תעבירי|העברי|שני|תשני)\s+(?:את\s+)?(?:ה)?(?:פנייה\s+של\s+|פניה\s+של\s+|תיק\s+של\s+|אירוע\s+של\s+)?(.+?)\s+ל(?:סטטוס\s+|מצב\s+|עמודה\s+|עמודת\s+)?"?(פנייה|פניה|הצעה\s+נשלחה|נשלחה\s+הצעה|נסגר|סגור|בוצע|ירד|ירדה|אבוד)"?$|^(?:ה)?(?:פנייה|פניה|תיק|אירוע)\s+(?:של\s+)?(.+?)\s+(נסגרה|נסגר|ירדה|ירד|בוצעה|בוצע|התבטלה|בוטלה)$|^(?:move|put|set)\s+(?:the\s+(?:lead|case|event)\s+(?:of\s+)?)?(.+?)\s+(?:to|as|in|into)\s+(?:status\s+|column\s+|the\s+)?(lead|quoted|quote\s+sent|won|closed|done|lost|dropped)$|^(?:mark|flag)\s+(?:the\s+(?:lead|case|event)\s+(?:of\s+)?)?(.+?)\s+as\s+(lead|quoted|won|closed|done|lost|dropped)$|^(?:the\s+)?(?:lead|case|event|enquiry|inquiry|deal)\s+(?:of\s+|for\s+|with\s+)?(.+?)\s+(?:is|was)\s+(won|closed|lost|dropped|done|cancelled|canceled)$|^(?:we\s+)?(won|lost)\s+(.+)$|^(.+?)\s+(?:is|was)\s+(won|lost)$|^(?:passe|mets|déplace|bascule)\s+(?:le\s+(?:dossier|lead)\s+(?:de\s+)?)?(.+?)\s+(?:en|à|dans|au)\s+(?:statut\s+|colonne\s+)?"?(demande|devis\s+envoyé|gagné|conclu|fait|terminé|perdu|abandonné)"?$|^marque\s+(?:le\s+(?:dossier|lead)\s+(?:de\s+)?)?(.+?)\s+comme\s+(demande|gagné|conclu|fait|terminé|perdu|abandonné)$|^(?:le|la)\s+(?:dossier|demande|lead|affaire)\s+(?:de\s+)?(.+?)\s+est\s+(gagnée?|conclue?|perdue?|abandonnée?|faite?|terminée?)$|^on\s+a\s+(gagné|perdu)\s+(.+)$|^(.+?)\s+(?:est|c'est)\s+(gagné|perdu|conclu|abandonné)$/i],
  // history
  ['history', /^(?:מה\s+(?:השתנה|עודכן|התעדכן|השתנו|קרה)|אילו\s+שינויים(?:\s+היו)?|מה\s+(?:ה)?היסטוריה)(?:\s+(היום|אתמול|לאחרונה|השבוע))?(?:\s+(?:ב|של\s+|באירוע\s+|בתיק\s+)(.+?))?(?:\s+(היום|אתמול|לאחרונה|השבוע))?$|^(?:what\s+(?:has\s+)?changed|what(?:'s|\s+is)\s+new|any\s+changes|latest\s+changes|what(?:'s|\s+is)\s+the\s+latest|show\s+(?:me\s+)?(?:the\s+)?history|show\s+(?:me\s+)?what\s+changed|what\s+happened)(?:\s+(today|yesterday|recently|lately|this\s+week))?(?:\s+(?:in|on|for|with|of|about|at)\s+(.+?))?(?:\s+(today|yesterday|recently|lately|this\s+week))?$|^(?:qu'est-ce\s+qui\s+a\s+changé|qu'est-ce\s+qui\s+a\s+été\s+modifié|qu'est-ce\s+qui\s+s'est\s+passé|quoi\s+de\s+neuf|quels\s+changements|montre(?:-moi)?\s+l'historique|les\s+derniers\s+changements)(?:\s+(aujourd'hui|hier|récemment|recemment|dernièrement|cette\s+semaine))?(?:\s+(?:dans|sur|pour|de|d'|chez)\s*(.+?))?(?:\s+(aujourd'hui|hier|récemment|recemment|dernièrement|cette\s+semaine))?$/i],
].map(([k, re]) => [k, loose(re)]);

const STATUS_WORDS = {
  'פנייה': 'פנייה', 'פניה': 'פנייה', 'הצעה נשלחה': 'הצעה נשלחה', 'נשלחה הצעה': 'הצעה נשלחה', 'נסגר': 'נסגר', 'סגור': 'נסגר', 'נסגרה': 'נסגר', 'בוצע': 'בוצע', 'בוצעה': 'בוצע',
  'ירד': 'ירד', 'ירדה': 'ירד', 'אבוד': 'ירד', 'התבטלה': 'ירד', 'בוטלה': 'ירד',
  lead: 'פנייה', quoted: 'הצעה נשלחה', 'quote sent': 'הצעה נשלחה', won: 'נסגר', closed: 'נסגר', done: 'בוצע', lost: 'ירד', dropped: 'ירד', cancelled: 'ירד', canceled: 'ירד',
  demande: 'פנייה', 'devis envoyé': 'הצעה נשלחה', gagné: 'נסגר', gagnée: 'נסגר', conclu: 'נסגר', conclue: 'נסגר', fait: 'בוצע', faite: 'בוצע', terminé: 'בוצע', terminée: 'בוצע', perdu: 'ירד', perdue: 'ירד', abandonné: 'ירד', abandonnée: 'ירד'
};
const WHEN_WORDS = { 'היום': 'today', today: 'today', "aujourd'hui": 'today', 'aujourd’hui': 'today', 'אתמול': 'yesterday', yesterday: 'yesterday', hier: 'yesterday', 'השבוע': 'week', 'this week': 'week', 'cette semaine': 'week',
  'לאחרונה': 'recent', recently: 'recent', lately: 'recent', 'récemment': 'recent', recemment: 'recent', 'dernièrement': 'recent' };
const norm = s => trim(str(s)).toLowerCase().replace(/\s+/g, ' ');

/** {kind, who, alt, ...} or null. `who`/`alt` name the event (alt = without a Hebrew ל/ב prefix); the screen resolves it. */
export function parseAction2(text) {
  const raw = polite(str(text).replace(/’/g, "'"), true); // line breaks stay: a pasted list of participants is several lines
  if (!raw || raw.length > 600) return null;
  const t = raw.replace(/[?!.]+$/, '').trim();
  if (t.length > 400) return null;
  for (const [kind, re] of R) {
    const m = re.exec(t); if (!m) continue;
    const g = m.slice(1).filter(x => x != null);
    const out = { kind };
    // the pasted list keeps its line breaks (core.trim would fold them)
    if (kind === 'partAdd') { Object.assign(out, whoOf(g[0])); out.text = str(g[1]).replace(/^\s+|\s+$/g, '').replace(/\s*(?:סיימתי|terminé|done)\s*$/i, ''); return out; }
    if (kind === 'rsNow' || kind === 'rsNext' || kind === 'remindersRead' || kind === 'urgent' || kind === 'reminders') return out;
    if (kind === 'live') { if (g[0]) Object.assign(out, whoOf(g[0])); return out; }
    if (kind === 'callSheet') { out.who = trim(g[0] || ''); if (g[1]) { const e = whoOf(g[1]); out.event = e.who; out.eventAlt = e.alt; } out.raw = trim(m[0].replace(/^.*?(?:דף\s+(?:ה)?קריאה|call\s*sheet|feuille\s+de\s+route)\s+(?:ל|של\s+|for\s+|of\s+|to\s+|pour\s+|de\s+|d['’]|à\s+)/i, '')); return out; }
    if (kind === 'fileFind') { out.what = trim(g[0] || ''); Object.assign(out, whoOf(g[1])); return out; }
    if (kind === 'caseMove') { let who = g[0], st = g[1]; if (STATUS_WORDS[norm(who)] && !STATUS_WORDS[norm(st)]) [who, st] = [st, who]; Object.assign(out, whoOf(who)); out.status = STATUS_WORDS[norm(st)] || ''; if (!out.status) return null; return out; }
    if (kind === 'history') {
      const words = g.map(norm); const when = words.map(w => WHEN_WORDS[w]).find(Boolean) || 'recent';
      const name = g.find(x => !WHEN_WORDS[norm(x)]);
      out.when = when; Object.assign(out, name ? whoOf(name) : { who: '', alt: '' }); return out;
    }
    Object.assign(out, whoOf(g[0]));
    return out;
  }
  return null;
}

/** The stored status word for a status she said, or ''. */
export function statusWord(w) { return STATUS_WORDS[norm(w)] || ''; }
